### ISSUE TITLE
Toggle Background Play

### ISSUE THREAD

**Issue by Pra-San** [ContriHUB/Music-Player#1]
Enable toggling of background play via the settings.

**Comment by samimshoaib01** [comment]
Before Background Play, music should be played inside app . I guess it's not there  . Correct me sir if I am wrong.


https://github.com/user-attachments/assets/8c404ab7-8fa3-48e6-9589-265945ae1864

**Comment by Pra-San** [comment]
@samimshoaib01  I have updated the repo. Pull the latest commit.

**Comment by samimshoaib01** [comment]
Sir I checked, Background play is already implemented I guess.

**Comment by Pra-San** [comment]
@samimshoaib01  ok your task is to create a settings page where a person can toggle background play on and off. I'll be giving you an extra day as well.

Someone else had implemented this before apparently, sorry for the inconvenience.

**Comment by samimshoaib01** [comment]
sue sir i will try to implement it

**Comment by samimshoaib01** [comment]
Sir , i implemented this , shall I request for this again ??

**Comment by samimshoaib01** [comment]
![Screenshot_2024-10-23-08-00-44-134_com.example.musicplayer.jpg](https://github.com/user-attachments/assets/59c53803-edd8-4f43-a2a7-2dfa8b98daa3)

![Screenshot_2024-10-23-08-00-50-988_com.example.musicplayer.jpg](https://github.com/user-attachments/assets/77453365-72d6-4b69-a0ae-2e57615d3d16)

Instead of new page I have added a switch to enable and disable background music play.

**Comment by Pra-San** [comment]
@samimshoaib01  yeah request for it again

**Comment by samimshoaib01** [comment]
Sir for now it says , Assignment Request for [Issue #1](https://github.com/ContriHUB/Music-Player/issues/1) of [Music-Player](https://github.com/ContriHUB/Music-Player) cannot be made by you currently. 

Further i want to ask that if i am allowed  to add functionality in app according to me or not.

**Comment by Pra-San** [comment]
@samimshoaib01  If you want to add a new feature/point out  a bug you can create a new issue yourself, or tell me and I will create one. or if you implement it with the current issue I will award bonus points as per your task done. Also take a look at #5  if you have the time.

**Comment by Pra-San** [comment]
@samimshoaib01  yeah request for it again.

**Comment by Pra-San** [comment]
@samimshoaib01 status?

**Comment by samimshoaib01** [comment]
Good evening sir, 
I tried to implement issues, but there were too much error regarding build.gradle , SDK version etc when trying to take permission , view binding , foreground services .

So i tried to fix . I have developed the ui and many more functionality upon which now issue can be assigned and will be easy to work for everyone.

Here are some glimpses of it :

![Screenshot_2024-10-24-22-40-52-318_com.example.musicplayer.jpg](https://github.com/user-attachments/assets/655e52d9-46eb-4f7f-9858-3bac4b272a57)

![Screenshot_2024-10-24-22-40-47-135_com.example.musicplayer.jpg](https://github.com/user-attachments/assets/8e5a713c-0fba-4a65-afca-72a9c004fdc2)

![Screenshot_2024-10-24-22-41-24-952_com.example.musicplayer.jpg](https://github.com/user-attachments/assets/4b1faeb3-4597-4aa1-be07-4dae9af02038)


So sir, kindly create New issues regarding this. 
It have many functionalities like 
1)Glide android library 
2)Can work with latest Android 
3) Navigation drawer 


I hope I will get bonus points for these

**Comment by Pra-San** [comment]
@samimshoaib01 yes... you will get bonus points for the stuff you have done. But first open a PR.
