### ISSUE TITLE
Fix Background Play

### ISSUE THREAD

**Issue by Pra-San** [ContriHUB/Music-Player#5]
Currently The app has some issues with background play. When something is being played and we go to the song list/ menu it stops playing i.e. when the activity changes.

**Comment by RITIK-CHAUDHRY** [comment]
@Pra-San is this issue assigned to someone??

**Comment by Pra-San** [comment]
@RITIK-CHAUDHRY yes

**Comment by samimshoaib01** [comment]
Is anyone working on this issue ?

**Comment by Pra-San** [comment]
Resolved
